### ISSUE TITLE
Clarify metadata bucket in the environment module

### ISSUE THREAD

**Issue by verdimrc** [awslabs/mlmax#13]
Clarify step 2, section `Setup Guide` in `modules/environment/README.md`, that user needs to create a new bucket or re-use an existing bucket, but the `deploy.sh` (or is it the CloudFormation?) must be able to write to this bucket.

**Comment by josiahdavis** [comment]
@verdimrc how is this for revised wording? 

> 2) Prepare a S3 bucket name in the same region to store cloudformation
> intermediate metedata. This could be an existing bucket or a new bucket. You
> must be able to write to this bucket.

**Comment by yihyap** [comment]
Can also explicitly mentioned that this is a different bucket from step 1

**Comment by josiahdavis** [comment]
How about this one? @verdimrc 

> Prepare a S3 bucket in the same region to store cloudformation
> intermediate metedata. This could be an existing bucket or a new bucket. You
> must be able to write to this bucket. This is a different bucket than the one mentioned in Step 1.
