### ISSUE TITLE
Add Support for CI/CD automation

### ISSUE THREAD

**Issue by yinsong1986** [awslabs/mlmax#23]
## Describe the feature you'd like
Add Support for CI/CD automation.

## What is the motivation for the feature?
This will enable the automation of the pipelines from development to deployment.

**Comment by josiahdavis** [comment]
Adding a comment to keep this one open.

**Comment by josiahdavis** [comment]
Adding a comment to keep open.

**Comment by verdimrc** [comment]
adding a test comment.

**Comment by yinsong1986** [comment]
Will work on it soon.

**Comment by josiahdavis** [comment]
Will work on it with you @yinsong1986

**Comment by yinsong1986** [comment]
nice, @josiahdavis! I started to commit some code in the `cicd-pipeline` branch.
