### ISSUE TITLE
Stop-gap solution to modular processing scripts.

### ISSUE THREAD

**Issue by verdimrc** [awslabs/mlmax#38]
### Describe the feature you'd like
What to do with this stop-gap `FrameworkProcessor` at https://github.com/aws-samples/smallmatter-package/tree/smproc-stopgap ? 

Given the context & motivation for MLMax, I'm inclined to snapshot that class into this repo, rather than having an external dependencies. Thoughts?

### What is the motivation for the feature?
Simplify modular processing scripts.

### Could you contribute? (Optional) 
Yes. Happy to snapshot that class into this repo.

**Comment by josiahdavis** [comment]
This is being handled by current PR: https://github.com/aws/sagemaker-python-sdk/pull/2251
