### ISSUE TITLE
Environment module deploy.sh to support region override

### ISSUE THREAD

**Issue by verdimrc** [awslabs/mlmax#52]
## 🐛 Bug report

- [x] I have checked that this issue has not already been reported.

### Describe the bug
`modules/environment/deploy.sh` only picks the region defined in the runtime environment (env vars or `~/.aws/config` entry). It does not allow user to deploy on a different region without changing their AWS CLI setup.

### To reproduce
Run ./deploy.sh on a bucket in a different region that what's configured in AWS CLI.

### Expected behavior
something like `./deploy.sh --region ap-southeast-2` even if `~/.aws/config` defaults to ap-southeast-1. Otherwise, this can impede / introduce friction for using the same account to deploy to several regions.

### System information
- **awscli version**: aws-cli/2.1.30 Python/3.9.2 Darwin/19.6.0 source/x86_64 prompt/off
- **SageMaker Python SDK version**: aws-cli/2.1.30 Python/3.9.2 Darwin/19.6.0 source/x86_64 prompt/off
- **Docker image**: N/A
- **Python version**:  aws-cli/2.1.30 Python/3.9.2 Darwin/19.6.0 source/x86_64 prompt/off

**Comment by yihyap** [comment]
Issue is fixed in #54
