### ISSUE TITLE
Cloudformation to setup permission for external account to a role

### ISSUE THREAD

**Issue by yapweiyih** [awslabs/mlmax#75]
## 🚀 Feature request

Cloudformation to setup permission for external account to a role.

E.g.
- Run cloudformation script with input `<external_aws_acct>` as parameter
- Cloudformation will create local role `arn:aws:iam::<internal_aws_acct>:role/CrossAccountRole`.
- External AWS account `<external_aws_acct>` can assume role `CrossAccountRole` on `<internal_aws_acct>`

This is tracked in branch `cross_account_permission`

**Comment by yapweiyih** [comment]
This issue can be closed and branch deleted given cross account feature is low priority? @josiahdavis

**Comment by josiahdavis** [comment]
Hi @yapweiyih yes we can close the issue.
