### ISSUE TITLE
Edit on Github links from documentation 404

### ISSUE THREAD

**Issue by RichardScottOZ** [awslabs/mlmax#83]
## 🐛 Bug report

- [x ] I have checked that this issue has not already been reported.

### Describe the bug
Edit on Github links from documentation 404 - is the branch name wrong?

### Expected behavior
Take you to the relevant github page.

**Comment by josiahdavis** [comment]
Thanks, good catch. You're right, it was pointing to an old branch. Updated.

(You might need to do hard refresh on your browser so "Edit on Github" button works.)
