### ISSUE TITLE
Github Workflow Test Error

### ISSUE THREAD

**Issue by yapweiyih** [awslabs/mlmax#87]
## 🐛 Bug report

- [✅  ] I have checked that this issue has not already been reported.

### Describe the bug
After pull request, github automated job workflow staled at `test` stage.

### To reproduce
Create a pull request/push new code change to trigger github workflow.

Error message:

> Run tox -e pytest
  tox -e pytest
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
GLOB sdist-make: /home/runner/work/uc-mlmax/uc-mlmax/setup.py
pytest create: /home/runner/work/uc-mlmax/uc-mlmax/.tox/pytest
pytest installdeps: -rrequirements.txt

### Expected behavior
Both lint and test jobs to complete successfully.

### System information
- **awscli version**: NA
- **SageMaker Python SDK version**: NA
- **Docker image**: NA
- **Python version**:  3.7

### Proposed Solution
Include specific python package version in top level directory`requirements.txt`.

> sagemaker[local]>=2.22.0
boto3>=1.9.213
pyyaml==5.4.1
stepfunctions>=2.0.0
fsspec==2021.8.1
s3fs==2021.8.1
scikit-learn==0.20.0
matplotlib==3.4.3
pandas==1.3.2
pytest==6.2.5
datatest==0.11.1
pytest-cov==2.12.1
numpy==1.21.2
loguru==0.5.3

**Comment by josiahdavis** [comment]
Thanks for raising the issue @yapweiyih. This should be fixed for new PRs now. See e.g., https://github.com/awslabs/mlmax/actions/runs/1242494324
